netparam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path, include
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('et/', views.et, name = 'et'),
    path('es/', views.es, name = 'es'),
    path('rs/', views.rs, name = 'rs'),
    path('courses/', views.courses, name = 'CoursePage'),
    path('courses/<str:name>/', views.courseinfo, name = 'CourseInfo'),
    path('service/', views.services, name = 'ServicePage'),
    path('service/<int:id>/', views.service_detail, name='ServiceDetail'),
    path('team/', views.teams, name = 'team'),
    path('about/', views.about, name = 'about'),
    path('career/', views.career, name = 'career'),
    # path('pay/', views.initiate_payment, name='pay'),
    # path('callback/', views.callback, name='callback'),
    # url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Netparam">
    <title>Netparam Technologies</title>

    
    <!-- CSS Files -->
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/line-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Icons -->
    <!-- <link href="{% static 'a/css/materialdesignicons.min.css' %}" rel="stylesheet" type="text/css" /> -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v2.1.9/css/unicons.css">
    <!-- Slider -->               
    <link rel="stylesheet" href="{% static 'a/css/owl.carousel.min.css' %}"/> 
    <link rel="stylesheet" href="{% static 'a/css/owl.theme.default.min.css' %}"/>    
    <!-- Main Css -->
    <link href="{% static 'a/css/style.css' %}" rel="stylesheet" type="text/css" id="theme-opt" />
    <!-- <link href="{% static 'a/css/colors/default.css' %}" rel="stylesheet" id="color-opt"> -->
    {% block style %} {% endblock %}
</head>
<body>

    <!-- Preloader -->
    <!-- <div class="preLoader"></div> -->
      <!-- Loader -->
      <div id="preloader">
        <div id="status">
            <div class="spinner">
                <div class="double-bounce1"></div>
                <div class="double-bounce2"></div>
            </div>
        </div>
    </div>
    <!-- Loader -->
  {% include 'navbar.html' %}      
<div style="">
    {% block content %} {% endblock %}
    

<!-- Counter Section Start -->
<div class="counters p-4" data-stellar-background-ratio="0.5" data-animate="fadeInDown" data-delay="0.5">
    <div class="overlay"></div>
    <div class="container">
      <div class="row"> 
        <div class="col-sm-6 col-md-3 col-lg-3">
          <div class="wow fadeInUp" data-wow-delay=".2s">
            <div class="facts-item"> 
              <div class="icon">
                <i class="lnr lnr-magic-wand"></i>
              </div>                
              <div class="fact-count">
                <h3><span class="counter">387</span>+</h3>
                <h4>Application Delivered</h4>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-3 col-lg-3">
          <div class="wow fadeInUp" data-wow-delay=".4s">
            <div class="facts-item">
              <div class="icon">
                <i class="lnr lnr-coffee-cup"></i>
              </div>                
              <div class="fact-count">
                <h3><span class="counter">155</span>+</h3>
                <h4>Project Completed</h4>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-3 col-lg-3">
          <div class="wow fadeInUp" data-wow-delay=".6s">
            <div class="facts-item">
              <div class="icon">
                <i class="lnr lnr-user"></i>
              </div>                
              <div class="fact-count">
                <h3><span class="counter">125</span>+</h3>
                <h4>Top Developers</h4>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-3 col-lg-3">
          <div class="wow fadeInUp" data-wow-delay=".8s">
            <div class="facts-item">
              <div class="icon">
                <i class="lnr lnr-heart"></i>
              </div>                
              <div class="fact-count">
                <h3><span class="counter">218</span>+</h3>
                <h4>Satisfied Clients</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Counter Section End -->

{% include 'footer.html' %}

    <!-- javascript -->
    <script src="{% static 'a/js/jquery-3.5.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="{% static 'a/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'a/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'a/js/scrollspy.min.js' %}"></script>
    

     <!-- JS Files -->
     <!-- <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script> -->
     
     <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script> -->
     <script src="{% static 'js/menu.min.js' %}"></script>
     <script src="{% static 'js/scripts.js' %}"></script>
     <script src="{% static 'js/custom.js' %}"></script>
     <script src="{% static 'js/wow.js' %}"></script>
     <script src="{% static 'js/fontawesome-all.min.js' %}"></script>
     <script src="{% static 'js/Edutrain.js' %}"></script>

     <script src="{% static 'plugins/typed.js/typed.min.js' %}"></script>
     <script src="{% static 'plugins/waypoints/jquery.waypoints.min.js' %}"></script>
     <script src="{% static 'plugins/waypoints/sticky.min.js' %}"></script>
     <script src="{% static 'plugins/swiper/swiper.min.js' %}"></script>
     <script src="{% static 'plugins/particles.js/particles.min.js' %}"></script>
     <script src="{% static 'plugins/particles.js/particles.settings.js' %}"></script>
     <script src="{% static 'plugins/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
     <script src="{% static 'plugins/parsley/parsley.min.js' %}"></script>
     <script src="{% static 'plugins/parallax/parallax.min.js' %}"></script>
     <script src="{% static 'plugins/retinajs/retina.min.js' %}"></script>

     <!-- Back to top -->
     <a href="#" class="btn btn-icon btn-soft-primary back-to-top"><i data-feather="arrow-up" class="icons"></i></a>
     <!-- Back to top -->

     <!-- SLIDER -->
     <script src="{% static 'a/js/owl.carousel.min.js' %} "></script>
     <script src="{% static 'a/js/owl.init.js' %} "></script>
     <!-- Icons -->
     <script src="{% static 'a/js/feather.min.js' %}"></script>
     <script src="https://unicons.iconscout.com/release/v2.1.9/script/monochrome/bundle.js"></script>
     <!-- Main Js -->
     <script src="{% static 'a/js/app.js' %}"></script>
     
</body>
</html>

templates/courseinfo.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<section style="background-color: #caacdd83">
    <div class="position-relative pt-7">
        <div class="container">
            <div class="row justify-content-center pb-5">
                <div class="col-sm-6 col-sm-8">
                    <!-- Section title -->
                    <div class="section-header text-center">
                        <h1 class="section-title wow fadeIn mb-2" data-animate="fadeInUp" data-delay=".12">{{course.name}} </h1>
                        <h3 class="section-subtitle wow fadeIn mt-2">{{course.subtitle}}</h3>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container pt-2">
        {% autoescape off %}
        {{course.description}}
        {% endautoescape %}
        
    
        <div class="row pb-7">
            <div class="col-sm-6">
                <a href="{{ course.syllabus.url }}" class="btn btn-outline-info mt-2">Download Syllabus</a>
                <a href="#" class = "btn btn-outline-success ml-3" >Apply Now</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/courses.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!--Course Section-->
<section class = "course">
    <div class="services-title position-relative pt-7" data-bg-img="{% static 'images/bg1.jpg' %}" >
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-6 col-lg-8">
                    <!-- Section title -->
                    <div class="section-title text-center">
                        <h1 class="text-white" data-animate="fadeInUp" data-delay=".1">Internship Training Programs</h1>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="services-wrap bg-white position-relative pt-5 pb-5">
        <div class="container">
            <!-- All Courses -->
            <div class="row">
                {% for course in courses %}
                <div class="card mr-3 ml-3 mb-3 col-md-2 text-center" data-animate="fadeInUp" data-delay=".1">
                    
                    <img src="{{ course.image.url }}" alt="..." data-no-retina>
                    <h4>{{course.name}}</h4>
                    <span>{{course.subtitle}}</span>                        
                    <a class="btn btn-outline-primary text-center" href="{% url 'website:CourseInfo' course.name %}">Apply Now</a>
                    <a class ="btn btn-outline-secondary text-center mt-3" href="{{ course.syllabus.url }}">More Info</a>
                        
                </div>
                {% endfor %}                                  
            </div>
        </div>
    </div>
</section>
<!-- End of Our services -->

{% endblock %}

templates/footer.html
{% load static %}        
        <!-- Footer Start -->
        <footer class="footer">
         <div class="container">
             <div class="row">
                 <div class="col-lg-4 col-12 mb-0 mb-md-4 pb-0 pb-md-2">
                     <a href="#" class="logo-footer">
                         <img src="{% static 'images/logo.svg' %}" alt="">
                     </a>
                     <p class="mt-4">Start working with Netparam that can provide everything you need to generate awareness, drive traffic, connect.</p>
                     <ul class="list-unstyled social-icon social mb-0 mt-4">
                         <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="facebook" class="fea icon-sm fea-social"></i></a></li>
                         <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="instagram" class="fea icon-sm fea-social"></i></a></li>
                         <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="twitter" class="fea icon-sm fea-social"></i></a></li>
                         <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="linkedin" class="fea icon-sm fea-social"></i></a></li>
                     </ul><!--end icon-->
                 </div><!--end col-->
                 
                 <div class="col-lg-3 col-md-4 col-12 mt-4 mt-sm-0 pt-2 pt-sm-0 offset-1">
                     <h4 class="text-light footer-head">Company</h4>
                     <ul class="list-unstyled footer-list mt-4">
                         <li><a href="page-aboutus.html" class="text-foot"><i class="mdi mdi-chevron-right mr-1"></i> About us</a></li>
                         <li><a href="page-services.html" class="text-foot"><i class="mdi mdi-chevron-right mr-1"></i> Services</a></li>
                         <li><a href="page-jobs.html" class="text-foot"><i class="mdi mdi-chevron-right mr-1"></i> Careers</a></li>
                         
                     </ul>
                 </div><!--end col-->
<!--                   
                 <div class="col-lg-3 col-md-4 col-12 mt-4 mt-sm-0 pt-2 pt-sm-0">
                     <h4 class="text-light footer-head">Usefull Links</h4>
                     <ul class="list-unstyled footer-list mt-4">
                         <li><a href="page-terms.html" class="text-foot"><i class="mdi mdi-chevron-right mr-1"></i> Terms of Services</a></li>
                         <li><a href="page-privacy.html" class="text-foot"><i class="mdi mdi-chevron-right mr-1"></i> Privacy Policy</a></li>
                         <li><a href="documentation.html" class="text-foot"><i class="mdi mdi-chevron-right mr-1"></i> Documentation</a></li>
                         <li><a href="changelog.html" class="text-foot"><i class="mdi mdi-chevron-right mr-1"></i> Changelog</a></li>
                         <li><a href="components.html" class="text-foot"><i class="mdi mdi-chevron-right mr-1"></i> Components</a></li>
                     </ul>
                 </div>end col -->

                 <div class="col-lg-4 col-md-4 col-12 mt-4 mt-sm-0 pt-2 pt-sm-0">
                     <h4 class="text-light footer-head">Newsletter</h4>
                     <p class="mt-4">Sign up and receive the latests via email.</p>
                     <form>
                         <div class="row">
                             <div class="col-lg-12">
                                 <div class="foot-subscribe form-group position-relative">
                                     <label>Write your email <span class="text-danger">*</span></label>
                                     <i data-feather="mail" class="fea icon-sm icons"></i>
                                     <input type="email" name="email" id="emailsubscribe" class="form-control pl-5 rounded" placeholder="Your email : " required>
                                 </div>
                             </div>
                             <div class="col-lg-12">
                                 <input type="submit" id="submitsubscribe" name="send" class="btn btn-soft-primary btn-block" value="Subscribe">
                             </div>
                         </div>
                     </form>
                 </div><!--end col-->
             </div><!--end row-->
         </div><!--end container-->
     </footer><!--end footer-->

   <!-- Footer
   <footer class="main-footer pt-4">
       <div class="container">
           <div class="row pb-3">
               <!-- Footer info 
               <div class="col-md-4">
                   <div class="footer-info">
                       <h3 data-animate="fadeInUp" data-delay="0">About Us</h3>
                       <p data-animate="fadeInUp" data-delay=".05">NTPL develops world class Websites, Android Apps, Iphone Apps, Cloud Based Application, Hybrid Mobile Apps & Big Data and Analysis. It works for the government and private projects and here the resources are placed from the top of the world.</p>
                       
                       
                   </div>
               </div>
               <div class="col-md-4">
                 <h3 data-animate="fadeInUp" data-delay="0">Contact Us</h3>
                 <ul class="footer-contacts list-unstyled">
                   <li data-animate="fadeInUp" data-delay=".1">
                       <i class="fas fa-phone"></i>
                       <span>
                         +91-7665010205
                       </span>
                       
                       
                   </li>
                   <li data-animate="fadeInUp" data-delay=".2">
                       <i class="fas fa-envelope"></i>
                       <span>netparam.hr@gmail.com</span>
                   </li>
                   <li data-animate="fadeInUp" data-delay=".3">
                       <i class="fas fa-map-marker"></i>
                       <span>IT-23, SITAPURA INDUSTRIAL AREA , EPIP OPPOSITE RICCO OFFICE, near GLOBE CIRCLE, Jaipur, Rajasthan 302022
                       </span>
                   </li>
               </ul>
               </div>
               <div class="col-md-4">
                 <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7123.0324356416395!2d75.819455075281!3d26.79168698271938!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x396dc9787b6e8159%3A0x7162ee3f35dc8f5a!2sNetparam%20Technologies%20Pvt.%20Ltd.!5e0!3m2!1sen!2sin!4v1614596236694!5m2!1sen!2sin" width="100%" height="270" frameborder="0" style="border:0" allowfullscreen=""></iframe>
               </div>
               <!-- End of Footer info 
           </div>
       </div>
   </footer> -->
   <!-- End of Footer -->

templates/mail_Contact.html
<html>
<body>
<p>Hello {{name}}</p>
<p>we got your message and we will reply you soon if needed</p>
</body>
</html>

templates/navbar.html
  {% load static %}
  <!-- Navbar STart -->
  <header id="topnav" class="scroll sticky">            
   <nav class="navbar navbar-expand-lg nav">
     <div class="container-fluid display-flex">
       <!-- Logo container-->
       <div class="col-md-12 display-flex">
           <a class="logo" href="{%url 'website:home'%}">
               <img src="{% static 'images/logo.svg' %}" alt="" >
           </a> 
      <ul class="navigation-menu" style="float:right;">
      <li  style="margin-top:15px;">
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navigation1"
      aria-controls="navigation1"
      aria-expanded="false"
      aria-label="Toggle navigation"
      {% comment %} style="background:white;" {% endcomment %}
      
    >
      <span style="color:white;">
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30 " fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
</svg>
      </span>
      </li>
    </button>
</ul>
    <span id="navigation1" class="collapse navbar-collapse" style="float:right;margin-right:0px;">
      {% comment %} <ul class="navbar-nav  ml-auto" id="myDIV" style="font-size: 20px; float:right;"> {% endcomment %}
       <!-- End Logo container-->  
       {% comment %} <div id="navigation"> {% endcomment %}
           <!-- Navigation Menu-->   
           <ul class="navigation-menu" style="float:right;">
               <li  style="margin-top:7px;"><a href="{%url 'website:home'%}">Home</a></li>
               <li  style="margin-top:7px;"><a href="{%url 'website:CoursePage'%}">Internship</a></li>
               <li  style="margin-top:7px;"><a href="{%url 'website:ServicePage'%}">Online&nbspExaminations</a></li>
               <li  style="margin-top:7px;"><a href="{%url 'website:ServicePage'%}">Services</a></li>
               <li  style="margin-top:7px;"><a href="{%url 'website:about'%}">About us</a></span></li>                
           </ul>
           <!--end navigation menu-->              
       </span><!--end navigation-->
       </div>
     </div><!--end container-->
   </nav>

   
</header><!--end header-->
<!-- Navbar End -->

   

templates/pay.html
{% extends 'base.html' %}

{% block content %}
<br>
<h2>Payment Home</h2>
{% if error %}
<br>
<h3>{{ error }}</h3>
{% endif %}
<br>
<form method="post">
    {% csrf_token %}
    <label for="username">Username: </label>
    <input type="text" name="username" required> <br>
    <label for="password">Password: </label>
    <input type="text" name="password" required> <br>
    <label for="amount">Amount: </label>
    <input type="number" name="amount" value="100"> <br> <br>
    <input type="submit" name="submit" value="Submit" required>
</form>

{% endblock %}

templates/redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Merchant Check Out Page</title>
</head>
<body>
    <h1>Please do not refresh this page...</h1>
        <form method="post" action="https://securegw-stage.paytm.in/order/process/" name="f1">
            <table>
                <tbody>
                    <input type="hidden" name="MID" value="{{ MID }}">
                    <input type="hidden" name="WEBSITE" value="{{ WEBSITE }}">
                    <input type="hidden" name="ORDER_ID" value="{{ ORDER_ID }}">
                    <input type="hidden" name="CUST_ID" value="{{ CUST_ID }}">
                    <input type="hidden" name="INDUSTRY_TYPE_ID" value="{{ INDUSTRY_TYPE_ID }}">
                    <input type="hidden" name="CHANNEL_ID" value="{{ CHANNEL_ID }}">
                    <input type="hidden" name="TXN_AMOUNT" value="{{ TXN_AMOUNT }}">
                    <input type="hidden" name="CALLBACK_URL" value="{{ CALLBACK_URL }}">
                    <input type="hidden" name="CHECKSUMHASH" value="{{ CHECKSUMHASH }}">
                </tbody>
            </table>
        <script type="text/javascript">
            document.f1.submit();
        </script>
        </form>
</body>
</html>

templates/servicedetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section">
    <div class="container">
      <div class="section-header">          
        <h1 class="section-title wow fadeIn mb-2" data-wow-duration="1000ms" data-wow-delay="0.3s"><span>{{service.name}}</span></h1>
        <p class="section-subtitle wow fadeIn" data-wow-duration="1500ms" data-wow-delay="0.35s">{{service.subtitle}}</p>
        <hr class="lines wow zoomIn" data-wow-delay="0.4s">
        
      </div>
    </div>
    <div class="row align-items-center text-center">
            
        <div class="col-sm-4 offset-1">
            <img src="{{service.image.url}}" alt="">
        </div>
        <div class="col-md-6 m-3">
            <div class="col-sm-12">
                <h2 class="mb-2">{{service.name}}</h2>
                <p class="text-justify">{{service.description}}</p>
            </div>
            
        </div>
        
    </div>
</section>


<!-- content close -->


{% endblock %}

templates/services.html
{% extends 'base.html' %}

{% block content %}
<section class="section" style="background-color:bisque">
    <div class="container mb-5">
      <div class="section-header">          
        <h2 class="section-title wow fadeIn mb-2" data-wow-duration="1000ms" data-wow-delay="0.3s">Our <span>Services</span></h2>
        <p class="section-subtitle wow fadeIn" data-wow-duration="1500ms" data-wow-delay="0.35s">Be Digital ready with our Fast and Cost-effective Services</p>
        <hr class="lines wow zoomIn" data-wow-delay="0.4s">
        
      </div>
    </div>

    <div class="container mt-4">
        <div class="row">
            {% for service in services %}
            <div class="col-lg-4">                
                <div class="col-lg-12 feature-box style-3 f-boxed shadow-right text-center">
                    <a href="{% url 'website:ServiceDetail' service.id %}">
                        <h4>{{service.name}}</h4>
                    </a>
                    <hr>
                    <p class="text-justify">{{service.subtitle}}</p>
                </div>                
            </div>       
            {% endfor %}     
        <div>
    </div>	
</section>


{% endblock %}